### ISSUE TITLE
Tilbakemeldinger på kodeoppgave

### ISSUE THREAD

**Issue by tholee** [Hattemaker/FizzBuzz#1]
Hei @Hattemaker 

Tusen takk for bevarelsen, og beklager at det har tatt litt tid før du mottar tilbakemelding. Det var veldig nyttig at du tok deg tid til å skrive litt om hvordan du har organisert kode, og litt om din erfaring med C#👍  Det at du  har begrenset erfaring med C#, men likevel bruker moderne features som null coalescing operator og Enumerable.Range er fint å se. Her følger en en liste over forslag til utbedringer som jeg håper du har tid og lyst til å gjennomføre. Utgangspunktet er bra, men med litt refaktorering kan det trolig bli enda bedre.

1. Legg til .gitignore og slett alle mapper av typen /bin, /obj og /.vs fra repository, da innholdet ikke er nødvendig å i repo.
2. Du skriver at FizzBuzzV2 inneholder mindre kodeduplisering, og det er bra! Men klarer du å unngå duplisering av regler også? Koden for FizzBuzz er veldig lik koden for Fizz og Buzz. En ev. regelendring vil medføre at kode må endres flere steder.
3. Se gjerne litt på navngivning også. Spesielt GetNumber.GetNewNumber forteller veldig lite om hva som egentlig skjer, og i hvilken konteks. Metoden returnerer faktisk heller ikke et tall, men en streng. Verb som prefiks er ofte passende på metoder, men sjelden klasser. "Get" forbindes også av mange med "getter" som bare henter data uten særlig grad av logikk eller prosessering. Det er vel ikke tilfelle her?
4. Innholdet i metodene FizzBuzz.RunGame og JazzFuzz.RunJazzFuzz er veldig like, bortsett fra litt ulike regler (kombinasjon av tall– og tekstverdi). Klarer du å konsolidere til en felles motor, og abstrahere vekk reglene? Et lite tips for å ikke henge seg opp i at sekvensene har ulik rekkefølge er å se på metoden LINQ Reverse. Målet her er å gjøre det enkelt å legge til endringer, og nye spill i fremtiden. Det vi ser etter her er om det kan gjøres uten "Open Closed Principle Violation", og DRY/WET violation.
5. Hva tenker du om en slik motor retunerer et resultatsett, og ikke selv har ansvaret for presentasjon med Console.Write?

Bare ta kontakt om noe er uklart, eller om du har andre spørsmål.

Med vennlig hilsen
Thomas Leela

**Comment by Hattemaker** [comment]
Hei @tholee 

Takk for tilbakemelding. Har endret på en del i prosjektet nå, så gjerne se over for ytteligere tilbakemelding.
1. Lagt til .gitignore og fjernet alt av unødvendige mapper/filer
2. Lagt til en setter så jeg kan endre på hvilke tall som skal endres, samt hvilken tekst som skal erstattes. Endret også måten stringen blir sammenkoblet.
3. Endret navn til noe jeg følte var mer passende til sitt formål.
4. Fjernet første iterasjon av begge programmene, lagde en ny versjon basert på FizzBuzzV2 som inheriter metoder for å unngå duplikasjon og oppnå segeregering.
5. Ser godt hensikten med å returnere dette til et sett for å senere printe ut settet, istedenfor at selve programmet printer det ut pr string. Dette kan jeg eventuelt ta en titt på.

Ser frem til å høre fra deg 🥇

**Comment by tholee** [comment]
Hei igjen @Hattemaker 

Fint forbedring dette👍

1. Det er fremdeles en del uønsket innhold i repository. Jeg finner mappen ./vs og flere /obj mapper
2. Målet er at koden følger Open Closed Principle slik at nye regler/spill kan legges til uten å måtte endre selve motoren. Jeg foreslår derfor at du samler FizzBuzzV2 og JazzFuzzV2 i et felles prosjekt. Du kan gjerne droppe V2-suffikeset da det ikke har noe verdi for koden eller beskrivelse av den. Fjern også alle andre eldre prosjekter som ikke lengre har verdi.
3. Klarer du å endre koden slik at du i FizzBuzz kan utvides med reglen "Quzz" med verdien 8 uten å måtte "åpne opp" og endre spillmotoren? Filen du kaller Rules, bør altså takle en samling med regler, og ikke være låst til 2 stk.

Bare ta kontak om noe er uklart🙂

**Comment by Hattemaker** [comment]
Hei @tholee 

Kan du opplyse meg om hvor du finner ./vs og /obj mapper? finner selv ikke disse i repoet.
Trodde forsåvidt også jeg har fjernet de forrige iterasjonene av prosjektet som ikke har noe verdi lenger, da de enste tre mappene/prosjektene som nå befinner seg i repoet er:
- FizzBuzzV2
- JazzFuzzV2
- FizzBuzzV2Test

Virker nesten som du får opp noen filer som jeg ikke får opp her. Opplys meg gjerne om hva du finner, så skal jeg gjøre endringer ut i fra det.

Jeg skal få samlet FizzBuzzV2 og JazzFuzzV2 i et felles prosjekt, droppe suffikset, samt implimentere regelen for "Quzz" så fort jeg har levert eksamen i morgen :) Er veldig mye å gjøre nå for tiden, da jeg har tre eksamner den kommende uken :)

**Comment by Hattemaker** [comment]
Hei @tholee 

har oppdatert repoet med en ny og bedre fungerende versjon, som tar en string og en int i et keyvaluepair, så man selv kan sette regler. Mer utfyllende beskrivelse står nevnt i README filen.

Oppdater meg gjerne dersom du fremdeles finner vs/obj mapper, da de skal være fjernet og lagt til i .gitignore :)

**Comment by tholee** [comment]
Hei igjen @Hattemaker 

Det har vært travle dager her også, så jeg beklager litt sen tilbakemelding. Jeg håper det gikk bra på eksamen. Når det gjelder vs/obj mappene ser jeg at det er løst nå. Kan det være at master branch ble endret til Master med stor forbokstav? Uansett er ikke det så viktig å finne årsak.

Besvarelsen du nå har levert nå passerer de aller fleste av kriteriene vi ser etter. Det er detaljer som kan raffineres ytterligere, men til å være første prosjekt med C# er det veldig bra!👍

Jeg gir beskjed til Andrea, og hun vil ta kontakt med deg.

**Comment by Hattemaker** [comment]
Ypperlig @tholee 😊 Takk for tilbakemeldinger og en morsom oppgave!
Venter i spenning på kontakt av Andrea.

Ha en fin dag!
